// Hand-authored representative sample content for the Phase D animation
// gallery — one real-looking item per section, used only to render a
// preview tile, never sent to the server.
export const PREVIEW_SAMPLES: Record<string, Record<string, unknown>> = {
  // These 7 are lifted directly from a real, delivered job's own props
  // (storage/jobs/job_eca240278c0f/_op_apply_style_props.json) rather than
  // hand-authored — already schema-valid, already proven to look right in
  // a real render. mountFrame/endFrame normalized to a flat 0-250 window
  // since gallery tiles don't have a real timeline position.
  dataCards: {
    title: "",
    x: 60, y: 1170, width: 960,
    mountFrame: 0, endFrame: 250,
    rows: [
      { label: "Coverage", value: 1.5, tone: "good", mountOffset: 11, prefix: "$", divideBy: 1.0, decimals: 1, unit: "M" },
      { label: "Premium", value: 8400.0, tone: "normal", mountOffset: 60, prefix: "$", divideBy: 1.0, decimals: 0 },
    ],
  },
  gauges: {
    title: "Policy Lapse Risk", leftLabel: "RENEW", rightLabel: "LAPSE", value: 0.9,
    x: 60, y: 1040, width: 960, mountFrame: 0, endFrame: 250,
  },
  countdowns: {
    value: 30.0, unitLabel: "DAYS", label: "RENEWAL", headline: "Renew in 30 days",
    x: 60, y: 1170, width: 960, mountFrame: 0, endFrame: 250,
  },
  calendarEvents: {
    year: 2026, month: 7, targetDay: 28, eventLabel: "RENEWAL",
    x: 180, y: 1170, width: 720, mountFrame: 0, endFrame: 250,
  },
  pills: {
    text: "Renew in 30 Days", x: 60, width: 960, y: 1490, mountFrame: 0, endFrame: 70,
  },
  zoneHeaders: {
    title: "REMINDER", fromFrame: 0, toFrame: 115, x: 60, y: 1040,
  },
  quotes: {
    text: "Renewing on time really matters.", mountFrame: 0, endFrame: 45,
  },
  beforeAfter: {
    kicker: "Medical Cost Over 10 Years",
    leftLabel: "In 2015",
    leftValue: 8000,
    leftPrefix: "$",
    rightLabel: "In 2025",
    rightValue: 32000,
    rightPrefix: "$",
    mountFrame: 0,
    secondRevealFrame: 40,
    endFrame: 250,
    x: 80,
    y: 900,
    width: 920,
  },
  barCharts: {
    title: "Monthly Premium by Plan",
    items: [
      { label: "Basic", value: 120, displayValue: "$120" },
      { label: "Plus", value: 220, displayValue: "$220" },
      { label: "Premier", value: 380, displayValue: "$380" },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  progressBars: {
    title: "Policy Setup",
    label: "Application Progress",
    percent: 80,
    subtext: "4 of 5 steps complete",
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  milestoneTracks: {
    title: "Policy Journey",
    milestones: [
      { label: "Purchased", sublabel: "Jan 2023" },
      { label: "Claim Filed", sublabel: "Jun 2024" },
      { label: "Claim Paid", sublabel: "Jul 2024" },
      { label: "Renewal Due", sublabel: "Jan 2026" },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  milestoneUnlocks: {
    value: 1000,
    suffix: "+",
    label: "Families Protected",
    icon: "award",
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  topicCards: {
    icon: "lightbulb",
    headline: "Most families are underinsured without realizing it",
    sub: "A short chat can uncover the gap in minutes",
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  cornerCards: {
    variant: "chat",
    appName: "WhatsApp",
    message: "Sure, let's get you a quote today!",
    mountFrame: 0,
    endFrame: 250,
  },
  testimonials: {
    quote: "She helped us find a plan that actually covered my daughter's treatment.",
    name: "Priya M.",
    role: "Client since 2021",
    initials: "PM",
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  trustBadges: {
    title: "Why Clients Trust Me",
    badges: [
      { icon: "shield", primary: "Licensed Agent", secondary: "CA License #0G12345" },
      { icon: "clock", primary: "8 Years Experience", secondary: "Serving Bay Area families" },
      { icon: "star", primary: "4.9/5 Rating", secondary: "200+ Client Reviews" },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  stepLists: {
    title: "How Claims Work",
    steps: [
      { label: "File Your Claim", sub: "Online or by phone", activateOffset: 0 },
      { label: "We Review Documents", activateOffset: 40 },
      { label: "Approval Decision", activateOffset: 80 },
      { label: "Funds Disbursed", sub: "Within 5 business days", activateOffset: 120 },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  rankedLists: {
    title: "Most Requested Coverage",
    items: [
      { label: "Health", value: 94, suffix: "%" },
      { label: "Life", value: 78, suffix: "%" },
      { label: "Critical Illness", value: 61, suffix: "%" },
      { label: "Dental", value: 45, suffix: "%" },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  checklists: {
    title: "What's Included",
    items: [
      { label: "Hospital stays covered", activateOffset: 0 },
      { label: "Outpatient visits", activateOffset: 30 },
      { label: "Prescription drugs", activateOffset: 60 },
      { label: "Annual health checkup", activateOffset: 90 },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  prosCons: {
    title: "This Plan's Pros & Cons",
    prosLabel: "Pros",
    consLabel: "Cons",
    pros: [
      "Covers pre-existing conditions after 12 months",
      "No medical exam required",
      "Locked-in premium for 5 years",
    ],
    cons: [
      "Higher deductible than Basic",
      "Waiting period applies",
      "Not available in all provinces",
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  comparisons: {
    title: "Basic vs Premier Plan",
    columns: [
      {
        label: "Basic Plan",
        labelEn: "BASIC",
        accent: "neutral",
        items: ["$120/month", "$5,000 deductible", "Basic dental"],
      },
      {
        label: "Premier Plan",
        labelEn: "PREMIER",
        accent: "good",
        items: ["$380/month", "$500 deductible", "Full dental + vision"],
      },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 1040,
    width: 960,
  },
  iconClusters: {
    title: "Stay Connected",
    items: [
      { icon: "chat", label: "WhatsApp Support" },
      { icon: "star", label: "5-Star Service" },
      { icon: "bolt", label: "Fast Claims" },
      { icon: "heart", label: "Family Focused" },
    ],
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
  locationPins: {
    place: "San Francisco",
    placeEn: "SAN FRANCISCO, CA",
    sub: "Now serving Bay Area families",
    mountFrame: 0,
    endFrame: 250,
    x: 60,
    y: 900,
    width: 960,
  },
};
